config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :agents
  resources :managers
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :functionalities
  resources :control_users

  root 'managers#index'

end

app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  before_action :authenticate_user!

  def index
    if current_user.admin?
      @users = User.all.order(id: :asc)
    elsif current_user.manager?
      @users = User.where(father_id: current_user.id).order(id: :asc)
    elsif current_user.agent?
      @users = User.where(father_id: current_user.id).order(id: :asc)
    else
      @users = User.where(father_id: current_user.id).order(id: :asc)
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to control_users_path, notice: 'User was successfully updated.' }
        format.json { render :index, status: :ok, location: @user }
      else
        format.html { render :edit }
      end
    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to control_users_path, notice: 'User was successfully created.' }
        format.json { render :index, status: :ok, location: @user }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:father_id, :manager_id, :email, :password, :password_confirmation, :agent_id, :profile_id, :active)
    end

end

app/views/control_users/_form.html.erb
<% if current_user.admin? %>
  <%= f.hidden_field :father_id, value: current_user.id %>
  Manager:<%= f.select :manager_id, Manager.all.collect{|m| [m.description, m.id]} %>
  <br />
  Choose a Profile:
  <%= f.collection_radio_buttons :profile_id, Profile.all, :id, :description %>
<% elsif current_user.manager? %>
  <%= f.hidden_field :father_id, value: current_user.id %>
  <%= f.hidden_field :manager_id, value: current_user.manager.id %>
  Manager:&nbsp; <%= current_user.manager.description %>
  <br />
  Choose a Profile:
  <%= f.collection_radio_buttons :profile_id, Profile.all, :id, :description %>
  <br />
  Agent:<%= f.select :agent_id, Agent.all.collect{|a| [a.name, a.id]} %>
<% else %>
  <%= f.hidden_field :father_id, value: current_user.id %>
  <%= f.hidden_field :manager_id, value: current_user.manager.id %>
  <%= f.hidden_field :profile_id, value: current_user.profile.id %>
  <%= f.hidden_field :agent_id, value: current_user.agent.id %>
  Manager:&nbsp; <%= current_user.manager.description %>
  <br />
  Profile:&nbsp; <%= current_user.profile.description %>
  <br />
  Agent:&nbsp; <%= current_user.agent.name %>
<% end %>

<div class="field">
  <%= f.label :email %><br>
  <%= f.text_field :email, required: true, autofocus: true %>
</div>

<div class="field">
  <%= f.label :password %><br>
  <%= f.password_field :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
</div>

<div class="field">
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation, required: true %>
</div>

<div class="field">
  <%= f.label :active %><br>
  <%= f.check_box :active %>
</div>

<hr />

<div class="actions">
  <%= f.submit %>
</div>

app/views/control_users/edit.html.erb
<h1>Editing User</h1>

<%= form_for(@user, url: control_user_path(@user)) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= render 'form', collection: [@view_edit = true, @adicionar = false], f: f %>
<% end %>

<%= link_to 'Back', control_users_path %>

app/views/control_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Father</th>
      <th>Manager</th>
      <th>Agent</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.active %></td>
        <td><%= user.father_id.present? ? user.father.email : "---" %></td>
        <td><%= user.manager_id.present? ? user.manager.description : "---" %></td>
        <td><%= user.agent_id.present? ? user.agent.name : "---" %></td>
        <td><%= user.profile_id.present? ? user.profile.description : "---" %></td>
        <td><%= link_to 'Edit', edit_control_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_control_user_path %>

app/views/control_users/new.html.erb
<h1>New User</h1>

<%= form_for(@user, url: control_users_path) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= render 'form', collection: [@view_edit = true, @adicionar = true], f: f %>
<% end %>

<%= link_to 'Back', control_users_path %>