config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :agents
  resources :managers
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :functionalities
  resources :control_users

  root 'managers#index'

end

app/models/functionality.rb
class Functionality < ActiveRecord::Base
end

app/controllers/functionalities_controller.rb
class FunctionalitiesController < ApplicationController
  before_action :set_functionality, only: [:show, :edit, :update, :destroy]

  # GET /functionalities
  # GET /functionalities.json
  def index
    @functionalities = Functionality.all
  end

  # GET /functionalities/1
  # GET /functionalities/1.json
  def show
  end

  # GET /functionalities/new
  def new
    @functionality = Functionality.new
  end

  # GET /functionalities/1/edit
  def edit
  end

  # POST /functionalities
  # POST /functionalities.json
  def create
    @functionality = Functionality.new(functionality_params)

    respond_to do |format|
      if @functionality.save
        format.html { redirect_to @functionality, notice: 'Functionality was successfully created.' }
        format.json { render :show, status: :created, location: @functionality }
      else
        format.html { render :new }
        format.json { render json: @functionality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /functionalities/1
  # PATCH/PUT /functionalities/1.json
  def update
    respond_to do |format|
      if @functionality.update(functionality_params)
        format.html { redirect_to @functionality, notice: 'Functionality was successfully updated.' }
        format.json { render :show, status: :ok, location: @functionality }
      else
        format.html { render :edit }
        format.json { render json: @functionality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functionalities/1
  # DELETE /functionalities/1.json
  def destroy
    @functionality.destroy
    respond_to do |format|
      format.html { redirect_to functionalities_url, notice: 'Functionality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_functionality
      @functionality = Functionality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def functionality_params
      params.require(:functionality).permit(:description)
    end
end

app/helpers/functionalities_helper.rb
module FunctionalitiesHelper
end

app/views/functionalities/_form.html.erb
<%= form_for(@functionality) do |f| %>
  <% if @functionality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@functionality.errors.count, "error") %> prohibited this functionality from being saved:</h2>

      <ul>
      <% @functionality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/functionalities/edit.html.erb
<h1>Editing Functionality</h1>

<%= render 'form' %>

<%= link_to 'Show', @functionality %> |
<%= link_to 'Back', functionalities_path %>

app/views/functionalities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Functionalities</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @functionalities.each do |functionality| %>
      <tr>
        <td><%= functionality.description %></td>
        <td><%= link_to 'Show', functionality %></td>
        <td><%= link_to 'Edit', edit_functionality_path(functionality) %></td>
        <td><%= link_to 'Destroy', functionality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Functionality', new_functionality_path %>

app/views/functionalities/new.html.erb
<h1>New Functionality</h1>

<%= render 'form' %>

<%= link_to 'Back', functionalities_path %>

app/views/functionalities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @functionality.description %>
</p>

<%= link_to 'Edit', edit_functionality_path(@functionality) %> |
<%= link_to 'Back', functionalities_path %>