config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :agents
  resources :managers
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :functionalities
  resources :control_users

  root 'managers#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TreePermission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <ul>
    <li>
      <%= link_to"#" do %>
      (
        <% if current_user.admin? %>
          Admin
        <% elsif current_user.manager? %>
          Manager
        <% elsif current_user.agent? %>
          Agent
        <% end %>
      )
      <% end %>
    </li>
    <li>
      <%= link_to '#' do %>
        <%= current_user.email %>
      <% end %>
    </li>
    <ul>
      <li><%= link_to "Add user", new_control_user_path %></li>
      <li><%= link_to "Add managers", new_manager_path %></li>
      <li><%= link_to "Add agents", new_agent_path %></li>
      <li><%= link_to "List users", control_users_path %></li>
      <li><%= link_to "Functionalities", functionalities_path %></li>
      <li><%= link_to "Profiles", profiles_path %></li>
      <li><%= link_to "Account", edit_user_registration_path %></li>
      <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
    </ul>
  </ul>
<% end %>

<%= yield %>

</body>
</html>